### PR TITLE
Prevent leaking hints towards the number of shares

### PR DESCRIPTION
**Pull request by farhaven**
If we simply increase the X coordinate by one for each share we generate, shares that become public leak hints towards the total
number of generated shares, and hence provide an upper bound on the number of shares that still need to be "collected" for secret
recovery.

### CODE REVIEW

**Comment by posener** [comment]
Hi.
Thanks for contributing.
Is this weakness documented somewhere?
Can you describe an attack that can benefit from it?

**Comment by farhaven** [comment]
Hi!

Apologies for the late reply. I don't think this is described as an existing weakness, but then again, it might not have that much practical impact anyway.

Essentially, the only scenario that would benefit from this change would be something along the lines of:

* Person A has information that they want to hide, so they generate a shared secret with, say, N=100 and K=50, encrypt their information and distribute the 100 shares to their confidantes.
* Person B wants to decrypt the information which they have obtained in encrypted form (for example by warrant and search in A's home)
* B needs to plan the resources they need to allocate to collect enough shares (since A was wise enough not to tell N or K to B when they were questioned) to recover the secret and decrypt A's confidential information.

Let's assume that B already has possession of a handful of shares, for example because some confidantes of A were arrested together with A.

With non-randomized X-coordinates, B can now estimate the order of magnitude of total shares in A's key (since the X-coordinates are simply a monotonically increasing counter on the shares), using a solution to the [German Tank Problem](https://en.wikipedia.org/wiki/German_tank_problem):

Assume that B has somehow obtained shares with the following 10 X coordinates:

	49, 67, 63, 52, 35, 39, 17, 84, 56, 37

Let k = 10 (since we have 10 coordinates) and m = 84 (the highest observed coordinate). Then, the Bayesian median of the population is

	N(med) = m + (m*log(2))/(k-1) = 90.46937368522616

and also:

	N(mean) = m - 1 + ((k-1)/(k-2)) = 84.125
	sigma   = sqrt(((k-1)(m-1)(m-k+1))/(k-3)(k-2)^2) = 11.182835220

which estimates the number of shares between roughly 73 and 95 (and slightly skewing it towards the high side), which isn't too far off the real number of shares.

Thus, B knows that they need to allocate enough resources to obtain roughly 95 warrants for keys (and to find the remaining confidantes through other means) to more or less guarantee enough shares for successful recovery of the secret.

If we randomize the X-coordinate in the share, B can't make that estimation, and has to guess how many resources to allocate, either allocating to many resource (and thus hindering B's other operations), or overstretching the allocated resources, thus prolonging the time until A's information can be decrypted.

I admit that this is a very "constructed" scenario, in that it probably does not apply to the vast majority of users of this package. It also does not prevent recovery of the secret for an adversary with enough resources, but it makes that recovery more cumbersome.

I'd be fine if you'd reject this PR though.

**Comment by posener** [comment]
It sounds like you know more about cryptography than I do.
However, the current implementation is according to the "official" algorithm.
I don't want to add any changes which might introduce weaknesses that I can't think of.
If you can bring this up in some forum with smarter people and have their advice, it would be nice, and we can add this feature as an option, I guess.

To my guts feeling, you can produce keys with `N=<really large number>` and `K=50`, and randomly keep 100 of them. Wouldn't this work out as well?

**Comment by farhaven** [comment]
I've thought about this a bit, and I think you're right. For any practical concern, your suggestion of just generating a very large number of secrets and throwing away almost all of them provides ~ the same improvements as my PR, and as you say, it doesn't require changing the core algorithm. That's always a bonus, but even more so when it comes to things that people might put a lot of trust into.

I'll close this PR, since your suggestion more than covers my use case. Thanks for taking the time to review this :)

**Pull request closed without merging**
